FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY  irrigation_service.py ./app/irrigation_service.py


EXPOSE 8000

CMD ["uvicorn", "app.irrigation_service:app", "--host", "0.0.0.0", "--port", "8000"]
